package net.spell_engine.api.item.armor;
import com.google.common.collect.*; import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents; import net.minecraft.entity.*; import net.minecraft.entity.attribute.*; import net.minecraft.item.*; import net.minecraft.recipe.Ingredient; import net.minecraft.registry.*; import net.minecraft.sound.SoundEvent; import net.minecraft.util.*; import net.spell_engine.api.item.*; import java.util.*; import java.util.function.*; import java.util.stream.*;
public class Armor {
 public static class Set<A extends ArmorItem>{public final String namespace;public final A head,chest,legs,feet;public boolean allowSpellPowerEnchanting=true;public Set(String ns,A h,A c,A l,A f){namespace=ns;head=h;chest=c;legs=l;feet=f;}public List<A> pieces(){return Stream.of(head,chest,legs,feet).filter(Objects::nonNull).collect(Collectors.toList());}public Identifier idOf(ArmorItem p){return new Identifier(namespace,p.getMaterial().getName()+"_"+p.getSlotType().getName());}public List<String> idStrings(){return pieces().stream().map(x->idOf(x).toString()).toList();}@Deprecated public Set<A> allowSpellPowerEnchanting(boolean a){allowSpellPowerEnchanting=a;return this;}public void register(RegistryKey<ItemGroup> group){for(var p:pieces())if(!Registries.ITEM.containsId(idOf(p)))Registry.register(Registries.ITEM,idOf(p),p);ItemGroupEvents.modifyEntriesEvent(group).register(c->{for(var p:pieces())c.add(p);});}}
 public record Entry(CustomMaterial material,Armor.Set armorSet,ItemConfig.ArmorSet defaults){public String name(){return material.getName();}@Deprecated public <T extends ArmorItem> Armor.Set<T> armorSet(Function<CustomMaterial,Armor.Set<T>> f,ArrayList<Entry> e){var s=f.apply(material);e.add(new Entry(material,s,defaults));return s;}public <T extends ArmorItem> Entry bundle(Function<CustomMaterial,Armor.Set<T>> f){return new Entry(material,f.apply(material),defaults);}public <T extends ArmorItem> Entry put(ArrayList<Entry> l){l.add(this);return this;}}
 public static class CustomMaterial implements ArmorMaterial{private static final EnumMap<ArmorItem.Type,Integer> BASE=new EnumMap<>(Map.of(ArmorItem.Type.BOOTS,13,ArmorItem.Type.LEGGINGS,15,ArmorItem.Type.CHESTPLATE,16,ArmorItem.Type.HELMET,11));private final String name;private final int durabilityMultiplier,enchantability;private final SoundEvent equipSound;private final Lazy<Ingredient> repair;private EnumMap<ArmorItem.Type,Integer> protection=new EnumMap<>(Map.of(ArmorItem.Type.BOOTS,0,ArmorItem.Type.LEGGINGS,0,ArmorItem.Type.CHESTPLATE,0,ArmorItem.Type.HELMET,0));private float toughness,knockback;public CustomMaterial(String n,int d,int e,SoundEvent s,Supplier<Ingredient> r){name=n;durabilityMultiplier=d;enchantability=e;equipSound=s;repair=new Lazy<>(r);}public int getDurability(ArmorItem.Type t){return BASE.get(t)*durabilityMultiplier;}public int getProtection(ArmorItem.Type t){return protection.get(t);}public int getEnchantability(){return enchantability;}public SoundEvent getEquipSound(){return equipSound;}public Ingredient getRepairIngredient(){return repair.get();}public String name(){return name;}@Deprecated public String getName(){return name;}public float getToughness(){return toughness;}public float getKnockbackResistance(){return knockback;}public void configure(ItemConfig.ArmorSet c){toughness=c.armor_toughness;knockback=c.knockback_resistance;protection=new EnumMap<>(Map.of(ArmorItem.Type.BOOTS,c.feet.armor,ArmorItem.Type.LEGGINGS,c.legs.armor,ArmorItem.Type.CHESTPLATE,c.chest.armor,ArmorItem.Type.HELMET,c.head.armor));}}
 public static void register(Map<String,ItemConfig.ArmorSet> configs,List<Entry> entries,RegistryKey<ItemGroup> group){for(var e:entries){var c=configs.get(e.name());if(c==null){c=e.defaults();configs.put(e.name(),c);}e.material().configure(c);for(var p:(List<ArmorItem>)e.armorSet().pieces()){if(p instanceof ConfigurableAttributes ca)ca.setAttributes(attributesFrom(c,p.getSlotType()));}e.armorSet().register(group);}}
 private static Multimap<EntityAttribute,EntityAttributeModifier> attributesFrom(ItemConfig.ArmorSet c,EquipmentSlot slot){var piece=switch(slot){case FEET->c.feet;case LEGS->c.legs;case CHEST->c.chest;case HEAD->c.head;default->c.head;};var uuid=MOD[Math.min(slot.getEntitySlotId(),3)];var b=ImmutableMultimap.<EntityAttribute,EntityAttributeModifier>builder();if(c.armor_toughness!=0)b.put(EntityAttributes.GENERIC_ARMOR_TOUGHNESS,new EntityAttributeModifier(uuid,"Armor modifier",c.armor_toughness,EntityAttributeModifier.Operation.ADDITION));if(c.knockback_resistance!=0)b.put(EntityAttributes.GENERIC_KNOCKBACK_RESISTANCE,new EntityAttributeModifier(uuid,"Armor modifier",c.knockback_resistance,EntityAttributeModifier.Operation.ADDITION));if(piece.armor!=0)b.put(EntityAttributes.GENERIC_ARMOR,new EntityAttributeModifier(uuid,"Armor modifier",piece.armor,EntityAttributeModifier.Operation.ADDITION));for(var a:piece.attributes){try{var attr=AttributeResolver.get(new Identifier(a.id));if(attr!=null)b.put(attr,new EntityAttributeModifier(uuid,"Armor modifier",a.value,a.operation));}catch(Exception ignored){}}return b.build();}
 private static final UUID[] MOD={UUID.fromString("845DB27C-C624-495F-8C9F-6020A9A58B6B"),UUID.fromString("D8499B04-0E66-4726-AB29-64469D734E0D"),UUID.fromString("9F3D476D-C118-4544-8365-64846904B48E"),UUID.fromString("2AD3F246-FEE1-4E67-B886-69FD380BB150")};
}
