package net.spell_engine.api.item.weapon;
import com.google.common.collect.*; import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents; import net.fabricmc.loader.api.FabricLoader; import net.minecraft.entity.attribute.*; import net.minecraft.item.*; import net.minecraft.recipe.Ingredient; import net.minecraft.registry.*; import net.minecraft.util.*; import net.spell_engine.api.item.*; import org.jetbrains.annotations.Nullable; import java.util.*; import java.util.function.Supplier;
public class Weapon {
 public static final class Entry { private final String namespace,name; private final CustomMaterial material; private final Item item; private final ItemConfig.Weapon defaults; private @Nullable String requiredMod; public Entry(String ns,String name,CustomMaterial mat,Item item,ItemConfig.Weapon defaults,@Nullable String req){namespace=ns;this.name=name;material=mat;this.item=item;this.defaults=defaults;requiredMod=req;} public Identifier id(){return new Identifier(namespace,name);} public Entry attribute(ItemConfig.Attribute a){defaults.add(a);return this;} public Entry requires(String m){requiredMod=m;return this;} public boolean isRequiredModInstalled(){return requiredMod==null||requiredMod.isEmpty()||FabricLoader.getInstance().isModLoaded(requiredMod);} public String name(){return name;} public CustomMaterial material(){return material;} public Item item(){return item;} public ItemConfig.Weapon defaults(){return defaults;} public @Nullable String requiredMod(){return requiredMod;} }
 public static class CustomMaterial implements ToolMaterial { public static CustomMaterial matching(ToolMaterials v,Supplier<Ingredient> repair){var m=new CustomMaterial();m.miningLevel=v.getMiningLevel();m.durability=v.getDurability();m.miningSpeed=v.getMiningSpeedMultiplier();m.enchantability=v.getEnchantability();m.ingredient=new Lazy<>(repair);return m;} private int miningLevel,durability,enchantability;private float miningSpeed;private Lazy<Ingredient> ingredient; public int getDurability(){return durability;} public float getMiningSpeedMultiplier(){return miningSpeed;} public float getAttackDamage(){return 0;} public int getMiningLevel(){return miningLevel;} public int getEnchantability(){return enchantability;} public Ingredient getRepairIngredient(){return ingredient==null?Ingredient.EMPTY:ingredient.get();} }
 public static void register(Map<String,ItemConfig.Weapon> configs,List<Entry> entries,RegistryKey<ItemGroup> group){for(var e:entries){var c=configs.get(e.name());if(c==null){c=e.defaults();configs.put(e.name(),c);}if(!e.isRequiredModInstalled())continue; if(e.item() instanceof ConfigurableAttributes ca)ca.setAttributes(attributesFrom(c)); if(!Registries.ITEM.containsId(e.id()))Registry.register(Registries.ITEM,e.id(),e.item());} ItemGroupEvents.modifyEntriesEvent(group).register(content->{for(var e:entries)if(e.isRequiredModInstalled())content.add(e.item());});}
 public static Multimap<EntityAttribute,EntityAttributeModifier> attributesFrom(ItemConfig.Weapon c){var b=ImmutableMultimap.<EntityAttribute,EntityAttributeModifier>builder();b.put(EntityAttributes.GENERIC_ATTACK_DAMAGE,new EntityAttributeModifier(ItemAccessor.damage(),"Weapon modifier",c.attack_damage,EntityAttributeModifier.Operation.ADDITION));b.put(EntityAttributes.GENERIC_ATTACK_SPEED,new EntityAttributeModifier(ItemAccessor.speed(),"Weapon modifier",c.attack_speed,EntityAttributeModifier.Operation.ADDITION));for(var e:attributesFrom(c.attributes).entrySet())b.put(e.getKey(),e.getValue());return b.build();}
 public static Map<EntityAttribute,EntityAttributeModifier> attributesFrom(List<ItemConfig.Attribute> attrs){var out=new LinkedHashMap<EntityAttribute,EntityAttributeModifier>();for(var a:attrs){if(a.value==0)continue;try{var id=new Identifier(a.id);var attr=AttributeResolver.get(id);if(attr==null)continue;var uuid=(id.getPath().contains("attack_damage")||id.getPath().contains("projectile_damage"))?ItemAccessor.damage():MISC;out.put(attr,new EntityAttributeModifier(uuid,"Weapon modifier",a.value,a.operation));}catch(Exception ignored){}}return out;}
 private static final UUID MISC=UUID.fromString("c102cb57-a7b8-4a98-8c6e-2cd7b70b74c1"); private abstract static class ItemAccessor extends Item{ItemAccessor(Settings s){super(s);}static UUID damage(){return ATTACK_DAMAGE_MODIFIER_ID;}static UUID speed(){return ATTACK_SPEED_MODIFIER_ID;}}
}
